applications:
  - name: django-app
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/filimon4uck/my-microservice-project.git
      path: final_project/charts/django-app
      targetRevision: final_project
      helm:
        valueFiles:
          - values.yaml
        parameters:
          - name: config.DATABASE_ENGINE
            value: postgresql
          - name: config.DATABASE_NAME
            value: mydb
          - name: config.DATABASE_USERNAME
            value: user
          - name: config.DATABASE_PASSWORD
            value: password
          - name: config.DATABASE_HOST
            value: db-host
          - name: config.DATABASE_PORT
            value: "5432"
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true



# repositories:
#   - name: django-app
#     url: https://github.com/filimon4uck/my-microservice-project.git
#     insecure: true
#     enableLfs: true
