replicaCount: 2

image:
  repository: 804054839611.dkr.ecr.eu-central-1.amazonaws.com/lesson-7-ecr
  tag: v1.0.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuThreshold: 70

ingress:
  enabled: false

config:
  DJANGO_SECRET_KEY: aaaaaaaaawddddddddawdddwdw
  DEBUG: "True"
  DJANGO_LOGLEVEL: info
  DJANGO_ALLOWED_HOSTS: "localhost, nginx"
  DATABASE_ENGINE: "postgresql_psycopg2"
  DATABASE_NAME: "dockerdjango"
  DATABASE_USERNAME: "user"
  DATABASE_PASSWORD: "dbpassword"
  DATABASE_HOST: "djangoapp-postgres"
  DATABASE_PORT: "5432"
