grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  persistence:
    enabled: false
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 7d
